project:
  type: website
  output-dir: docs

website:
  title: "Sophia's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - Simplex
      - brand
    css: styles.css
    toc: true



